import {
  Topbar,
  TailwindIndicator,
  Navbar,
  Footer,
  CopyRight,
  License,
} from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Western Sydney | Vocational Training Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Topbar />
        <Navbar />
        <TailwindIndicator />
        <main>{children}</main>
        <License />
        <Footer />
        <CopyRight />
      </body>
    </html>
  );
}
